const ONE_SECOND_MILLISECONDS = 1000
const ONE_MINUTE_SECONDS = 60

export const milliTimes = {
  ZERO: 0,
  ONE_SECOND: ONE_SECOND_MILLISECONDS,
  ONE_MINUTE: ONE_SECOND_MILLISECONDS * ONE_MINUTE_SECONDS,
  FIVE_MINUTE: ONE_SECOND_MILLISECONDS * ONE_MINUTE_SECONDS * 5,
} as const
