const ONE_SECOND_MILLISECONDS = 1000;
const ONE_MINUTE_SECONDS = 60;

export const milliTimes = {
  ZERO: 0,
  ONE_SECOND: ONE_SECOND_MILLISECONDS,
  FIVE_SECONDS: ONE_SECOND_MILLISECONDS * 5,
  THIRTY_SECONDS: ONE_SECOND_MILLISECONDS * 30,
  ONE_MINUTE: ONE_SECOND_MILLISECONDS * ONE_MINUTE_SECONDS,
  THREE_MINUTE: ONE_SECOND_MILLISECONDS * ONE_MINUTE_SECONDS * 3,
  FIVE_MINUTE: ONE_SECOND_MILLISECONDS * ONE_MINUTE_SECONDS * 5,
} as const;
